version: '3'
services:
  pbapp:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '5173:5173'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes: 
      - ./server:/app
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
